totaljs/framework

- utils.js
I do not know if you want to add that, so I post it just in case
> Add capitalize

- utils.js
> Add IsAlphaNumeric prototype

- index.js
Send args (array) to the new worker. Get the args via process.argv
> Added args to worker

- builders.js
- test/test-builders.js
improved performance and memory usage by schema instances
added|modified JSDoc
added new schema tests
added SchemaBuilderEntity.instancePrototype
> SchemaInstance

- builders.js
- test/test-builders.js
> Fixed clone

- builders.js
In some cases will be pageFrom = 0, but I think it can't be 0.
> Pagination fixed for first page.

- builders.js
> Revert "Pagination fixed for first page."

- utils.js
Can be really useful in view if a user put html tags in text.
> Add removeHtmlTags

- index.js
- internal.js
We can now use the magic `@{absolute()}` function in our view to prepend base url to our styles or scripts
--- Usage ---
`@{absolute(['default.js', 'home.js'], 'http://localhost:8000')}`
Tested, it worked like charm.
> Adding absolute function in our view

- index.js
Again, complements for the code !!!
It looks so complete and beautifull.
> fixed typo's

- .travis.yml
> use nodes 6.11 on Travis

- test/run.sh
- test/test-builders.js
- test/test-css.js
- test/test-framework-debug.js
- test/test-framework-release.js
- test/test-javascript.js
- test/test-utils.js
Travis tests always success now. 
How about let it fail on tests failed?
1. short circuit if the test failed
2. run.sh's exit code will be `1` if any test failed
> Failable Travis test

- .editorconfig
- debug.js
- index.js
customize directories, fix debug.js
> customize directories, fix debug.js

- debug.js
Monitor model files change in development environment.
> Monitor model files change

- test.js
calculate test count in logger base on #557
> calculate test count in logger

- test/test-utils.js
- utils.js
fixing test comment
fixing U.ls* string and RegExp filter
removed code duplication
i also removed the relative paramater from the FileList.onFilter callback
(i dont know where/if it was used - but it was not working)
> Test utils

- nosql.js
Adding data before modification/update to modify&update event.
> Add old document to modify & update events.

- bin/totaljs
> Revert "Added Openplatform empty project command to totaljs bin file."

- internal.js
If available, the controller is passed to the modificator, so you can access its properties or set another ones depending on needs
> Allow modificators to access controller

- test.js
> Added -c command line switch to test.js for color logs.

- utils.js
console.log((50).VAT(20));
// OK -> 41.67 (NEW)
// WRONG --> 41.66 (OLD)
console.log((101).VAT(20));
// OK -> 84.17 (NEW)
// WRONG --> 84.16 (OLD)
Check here: https://vypocetdph.com/
> fixed number.VAT() calculation

- index.js
I've tried to improve time complexity of F.schedules as for #751, please let me know what do you think, there are still some improvements that can be done, for example a better management of `owner` property. But I'm still quite unfamiliar with internal framework's code. So, at moment, this is the best I can do.
> Improve time complexity for F.schedules management

- index.js
Just forgot to to change this line
> FIX: schedule id attribute does not exists anymore

- package.json
- readme.md
@hethvik (https://huntr.dev/users/hethvik) has fixed a potential Command Injection vulnerability in your repository 🔨. For more information, visit our website (https://huntr.dev/) or click the bounty URL below...
Q | A
Version Affected | *
Bug Fix | YES
Original Pull Request | https://github.com/418sec/framework/pull/1
Vulnerability README | https://github.com/418sec/huntr/blob/master/bounties/npm/total.js/1/README.md
`total.js` is vulnerable to `Command Injection`.
Command injection vulnerabilities typically occur when:
1. Data enters the application from an untrusted source.
2. The data is part of a string that is executed as a command by the application.
3. By executing the command, the application gives an attacker a privilege or capability that the attacker would not otherwise have. …
> Security Fix for Command Injection - huntr.dev

- debug.js
https://nodejs.org/api/process.html#processexitcode
> Process.exit() Deprecated

- index.js
https://nodejs.org/api/process.html#processexitcode
> node process.exit() deprecated
